---
- name: Add percona yum repository
  yum:
    name: "http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm"
    state: present

- name: install percona-toolkit
  yum:
    name: percona-toolkit
    state: present
