- name: install redis
  apt:
    name: redis
    state: present

- copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644

- systemd:
    name: redis-server.service
    enabled: yes
    state: started
