---
- name: install sysstat
  yum:
    name: sysstat
    state: present

- name: install dstat
  yum:
    name: dstat
    state: present

- name: install htop
  yum:
    name: htop
    state: present
